todolist/urls.py
from django.contrib import admin
from django.urls import path

from core import views

urlpatterns = [
	path('', views.index, name='index'),
    path(r'todo_create/', views.TodoCreateView.as_view(), name='todo_create'),
    path(r'task_create/', views.TaskCreateView.as_view(), name='task_create'),
	path(r'todo_delete/<slug>/', views.todo_delete, name='todo_delete'),
    path(r'todo_update/<slug>/', views.TodoUpdateView.as_view(), name='todo_update'),
    path(r'task_delete/<slug>/', views.task_delete, name='task_delete'),
    path(r'task_update/<slug>/', views.TaskUpdateView.as_view(), name='task_update'),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Todo (models.Model):
	
	name = models.CharField('List', max_length=200)
	slug = models.SlugField('Id', max_length=200, unique=True)
	done = models.BooleanField('Done')

	created = models.DateTimeField('Crieted', auto_now_add=True)
	modified = models.DateTimeField('Modified', auto_now=True)

	class Meta:
		verbose_name='To do'
		verbose_name_plural='To do\'s'
		ordering=['modified']

	def __str__(self):
		return self.name

class Task (models.Model):

	name = models.CharField('Task', max_length=200)
	slug = models.SlugField('Id', max_length=200, unique=True)
	done = models.BooleanField('Done', default=False, blank=True)
	todo = models.ForeignKey('core.ToDo', on_delete=models.CASCADE, verbose_name='To do')
	deadline = models.DateTimeField('Deadline')

	created = models.DateTimeField('Created', auto_now_add=True)
	modified = models.DateTimeField('Modified', auto_now=True)

	class Meta:
		verbose_name='Task'
		verbose_name_plural='Tasks'
		ordering=['modified']

	def __str__ (self):
		return self.name

core/forms.py
from django import forms

from .models import Todo, Task

class TodoForm (forms.ModelForm):
	class Meta:
		model= Todo
		fields = '__all__'

class TaskForm (forms.ModelForm):
	class Meta:
		model = Task
		fields = '__all__'

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect

from django.urls import reverse_lazy
from django.views import generic

from .models import Todo, Task
from .forms import TodoForm, TaskForm
# Create your views here.
def index (request):
	context = {
		'todos' : Todo.objects.prefetch_related('task_set'),
		'todo_form'	: TodoForm(),
		'task_form' : TaskForm(),
	}
	return render(request, 'index.html', context)

class TodoCreateView (generic.CreateView):
	model = Todo
	form_class = TodoForm
	success_url = reverse_lazy ('index')

class TaskCreateView (generic.CreateView):
	model = Task
	form_class = TaskForm
	success_url = reverse_lazy ('index')


def todo_delete (request, slug):
	todo = Todo.objects.get(slug=slug)
	todo.delete()
	return HttpResponseRedirect('/')

def task_delete (request, slug):
	task = Task.objects.get(slug=slug)
	task.delete()
	return HttpResponseRedirect('/')

class TodoUpdateView (generic.UpdateView):

	model = Todo
	template_name = 'todo_update.html'
	fields = ['name', 'slug', 'done']
	success_url = reverse_lazy('index')

	def get_context_data(self, **kwargs):
		context = super(TodoUpdateView, self).get_context_data(**kwargs)
		context['Todo'] = get_object_or_404(Todo, slug=self.kwargs['slug'])
		return context

class TaskUpdateView (generic.UpdateView):

	model = Task
	template_name = 'task_update.html'
	fields = ['name', 'slug', 'todo', 'deadline', 'done']
	success_url = reverse_lazy('index')

	def get_context_data(self, **kwargs):
		context = super(TaskUpdateView, self).get_context_data(**kwargs)
		context['Task'] = get_object_or_404(Task, slug=self.kwargs['slug'])
		return context

core/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>TODO App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.0.3/css/bootstrap-datetimepicker.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.0.3/css/bootstrap-datetimepicker.min.css"/>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.0.3/js/bootstrap-datetimepicker.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Muli:300' rel='stylesheet' type='text/css'>

<header class="page-title">
  <h1>  <i class="material-icons">view_list</i>
        TODO</h1>
  <div class="tag"> An easy way to manage your work.</div>
</header>


{% block container %}
{% endblock %}

<script  src="{% static 'js/index.js' %}"></script>
  <script type="text/javascript">
    $("#id_deadline").datetimepicker();
  </script>
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block container %}
<section class="todo-list-container">
  <div class="todo-in-progress">
    <h2> Working Lists</h2>
    <ul ondragstart="" class="todo-list" id="target">

      {% for todo in todos %}
      {% if not todo.done %}
        <li draggable="true" class="todo-item high">
          <div class="card">

            <h3 class="todo-title">  
              <span class="title">{{ todo }} </span>
              <a href="{% url 'todo_delete' slug=todo.slug %}" class="fa fa-trash pull-right" style="color:#fff; text-decoration:none;"></a>
              <a href="{% url 'todo_update' slug=todo.slug %}" class="fa fa-pencil pull-right" style="color:#fff; text-decoration:none;"></a>
            </h3>
            <ul class="list-group list-group-horizontal">
              {% for task in todo.task_set.all %}
                <li>
                    <li  class="list-group item">
                      <div>
                        <label style="display: inline-block; margin-right:15px;">
                          <input class="" type="checkbox" value="" {% if task.done %} checked {% endif %}/> {{task.name}} </label>
                        <p style="display:inline-block;">{{task.deadline}}</p>
                        <a href="{% url 'task_delete' slug=task.slug %}" class="fa fa-trash" style="color:#000; text-decoration:none; float:right; margin-left:5px;"></a>
                        <a href="{% url 'task_update' slug=task.slug %}" class="fa fa-pencil" style="color:#000; text-decoration:none; float:right;"></a>
                      </div>
                    </li>
                </li>
              {% endfor %}
              <button type="submit" data-toggle="modal" data-target="#exampleModal" data-whatever="{{ todo.id }}" class="btn btn-default" style="margin-top:15px;">Add Task</button>
              <span type="submit" class="todo-priority"> Do it! </span>
            </ul>
            <br/>
          </div>

        </li>
      {% endif %}
      {% endfor %}
      <li class="todo-item new">
         <div class="card" data-toggle="modal" data-target="#myModal" >
          
           <h3 class="todo-title"> <span class="action">
                     <i class="complete material-icons md-36 md-light">add_circle_outline</i>
                   </span> 
                   <span class="title">Add list</span></h3>
         </div>
 
       </li>
       <li>
       
       </li>
    </ul>
  </div>
  
  <!-- Modal ToDo-->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add list</h4>
        </div>
        <div class="modal-body">
          <form action="{% url 'todo_create' %}" method="post">
            <fieldset>
              {% csrf_token %}
              {% for field in todo_form %}
                <div class="{% if field.errors %} has-errors {% endif %}">
                  <label for="{{field.auto_id }}" class="col-md-3 control-label" style="display: inline-block; margin-right: 15px;">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field %}
                    {% for error in field.errors %}
                      <span class="help-block">{{error}}</span>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}
              <div class="modal-footer">
                <button type="submit" class="btn btn-default">Create</button>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal Task-->
  <div class="modal fade" id="exampleModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add task</h4>
        </div>
        <div class="modal-body">
          <form action="{% url 'task_create' %}" method="post">
            <fieldset>
              {% csrf_token %}
              {% for field in task_form %}
                  <div class="{% if field.errors %} has-errors {% endif %}">
                    <label for="{{field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-9">
                      {% render_field field class='control-label' %}
                      {% for error in field.errors %}
                        <span class="help-block">{{error}}</span>
                      {% endfor %}
                    </div>
                  </div>
              {% endfor %}
              <div class="modal-footer">
                <button type="submit" class="btn btn-default">Create</button>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="todo-completed">
    <ul class="todo-list-completed">
      <h2> Completed Lists </h2>
      {% for list in todos %}
        {% if list.done %}
          <li class="todo-item high">
            <div class="icon-check">
              <i class="pad-15 material-icons md-36 md-light">check_circle</i>
            </div>

            <div class="icon-delete">
              <a class="pad-15 material-icons md-36 md-light" href="{% url 'todo_delete' slug=list.slug %}">delete</a>
            </div>
            <div class="content">
              {{ list.name }}
            </div>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
</section>

<script type="text/javascript">
$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('#id_todo').val(recipient)
})
</script>

{% endblock %}

core/templates/task_update.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block container %}
<!-- Modal Task-->
  <div class="" id="myModal2">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <a href="{% url 'index' %}" type="button" class="close" data-dismiss="modal">&times;</a>
          <h4 class="modal-title">Add task</h4>
        </div>
        <div class="modal-body">
          <form action="" method="post">
            <fieldset>
              {% csrf_token %}
              {% for field in form %}
                <div class="{% if field.errors %} has-errors {% endif %}">
                  <label for="{{field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class='control-label' %}
                    {% for error in field.errors %}
                      <span class="help-block">{{error}}</span>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}
              <div class="modal-footer">
                <button type="submit" class="btn btn-default">Update</button>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

core/templates/todo_update.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block container %}
  <div class="">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <a href="{% url 'index' %}" type="button" class="close" data-dismiss="modal">&times;</a>
          <h4 class="modal-title">Add list</h4>
        </div>
        <div class="modal-body">
          <form action="" method="post">
            <fieldset>
              {% csrf_token %}
              {% for field in form %}
                <div class="{% if field.errors %} has-errors {% endif %}">
                  <label for="{{field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field %}
                    {% for error in field.errors %}
                      <span class="help-block">{{error}}</span>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}
              <div class="modal-footer">
                <button type="submit" class="btn btn-default">Update</button>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}